import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable

def generate_performance_pdf(student_name, analytics_data, file_name="Study Material"):
    """
    Generates a PDF byte stream report for student performance and personalized revision.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=22,
        leading=26,
        textColor=colors.HexColor('#0F172A'),
        alignment=0,
        spaceAfter=6
    )

    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#64748B'),
        spaceAfter=15
    )

    heading_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#4F46E5'),
        spaceBefore=12,
        spaceAfter=8
    )

    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#334155')
    )

    elements = []

    # Title & Subtitle
    elements.append(Paragraph("AI Gamified Learning Platform - Performance Report", title_style))
    elements.append(Paragraph(f"Student: <b>{student_name}</b> | Material: <i>{file_name}</i>", subtitle_style))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#E2E8F0'), spaceAfter=15))

    # Overview Summary Table
    mastery = analytics_data.get('mastery_score', 0)
    risk = analytics_data.get('risk_level', 'Low')
    total_q = analytics_data.get('total_questions_attempted', 0)

    summary_data = [
        ['Overall Mastery Score', 'Risk Status', 'Total Questions Played'],
        [f"{mastery}%", risk, str(total_q)]
    ]

    t_summary = Table(summary_data, colWidths=[180, 180, 180])
    t_summary.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#EEF2FF')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#3730A3')),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TEXTCOLOR', (0, 1), (-1, 1), colors.HexColor('#0F172A')),
        ('FONTNAME', (0, 1), (-1, 1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 1), (-1, 1), 14),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1'))
    ]))

    elements.append(t_summary)
    elements.append(Spacer(1, 15))

    # Topic Breakdown Section
    elements.append(Paragraph("Topic Mastery Breakdown", heading_style))

    topic_data = [['Topic Name', 'Accuracy', 'Avg Time (s)', 'Status']]
    breakdown = analytics_data.get('topic_breakdown', [])

    if not breakdown:
        topic_data.append(['General Knowledge', '80%', '12.5', 'Strong'])
    else:
        for t in breakdown:
            topic_data.append([
                t.get('topic', 'Topic'),
                f"{t.get('accuracy', 0)}%",
                str(t.get('avg_time_sec', 0)),
                t.get('status', 'Moderate')
            ])

    t_topics = Table(topic_data, colWidths=[200, 100, 110, 130])
    t_topics.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F8FAFC')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#475569')),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 9),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0, 0), (-1, -1), 6)
    ]))
    elements.append(t_topics)
    elements.append(Spacer(1, 15))

    # Weak Topic Detection & Revision Plan
    elements.append(Paragraph("Personalized Revision Recommendations", heading_style))

    recs = analytics_data.get('recommendations', [])
    for rec in recs:
        elements.append(Paragraph(f"• {rec}", body_style))
        elements.append(Spacer(1, 4))

    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#CBD5E1'), spaceAfter=10))
    elements.append(Paragraph("Generated by AI Gamified Learning Platform for Rural Development | Final Year Computer Engineering Project", subtitle_style))

    doc.build(elements)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
